import { NextRequest, NextResponse } from "next/server";
import { updateTrustState, getTrustState } from "@/lib/trust-store";
import { addIssueComment, updateAgent } from "@/lib/paperclip";

// Store active sessions keyed by companyId
const activeSessions = new Map<
  string,
  {
    agentKey: string | null;
    agentAddress: string;
    status: "pending" | "completed" | "failed";
  }
>();

export async function POST(req: NextRequest) {
  const { companyId, mainOperatorId, issueId, action } = await req.json();

  // Helper: mark the main operator agent as self-verified in Paperclip
  async function markAgentVerified(operatorId: string | undefined) {
    if (!operatorId) return;
    try {
      await updateAgent(operatorId, {
        status: "active",
        metadata: { selfVerified: true, selfVerifiedAt: new Date().toISOString() },
      });
    } catch {
      // Non-critical — don't block verification flow
    }
  }

  if (!companyId) {
    return NextResponse.json({ error: "companyId required" }, { status: 400 });
  }

  try {
    if (action === "start") {
      // Clear any previous session and reset self-verification state
      // so that check polling doesn't find stale verified status
      activeSessions.delete(companyId);
      updateTrustState(companyId, {
        selfVerified: false,
        selfVerifiedAt: null,
        selfAgentAddress: null,
      });

      const { requestRegistration } = await import("@selfxyz/agent-sdk");
      const state = getTrustState(companyId);
      if (!state.treasuryAddress) {
        return NextResponse.json(
          { error: "Company treasury not initialized. Deploy company treasury first." },
          { status: 400 }
        );
      }

      const session = await requestRegistration({
        mode: "linked",
        network: "mainnet",
        humanAddress: state.treasuryAddress as `0x${string}`,
        agentName: `Main Operator - ${mainOperatorId || "agent"}`,
        disclosures: {
          minimumAge: 18,
        },
      });

      // Export the agent key generated by the session
      let agentKey: string | null = null;
      try {
        agentKey = await session.exportKey();
      } catch {
        // exportKey may not be available yet
      }

      // Store session info for polling
      activeSessions.set(companyId, {
        agentKey,
        agentAddress: session.agentAddress,
        status: "pending",
      });

      // Persist agent address in trust store so confirm works even after hot-reload
      updateTrustState(companyId, { selfAgentAddress: session.agentAddress });

      // Start background wait — but don't block on it
      session
        .waitForCompletion({ timeoutMs: 300_000, pollIntervalMs: 3000 })
        .then(async () => {
          const entry = activeSessions.get(companyId);
          if (entry) entry.status = "completed";

          updateTrustState(companyId, {
            selfVerified: true,
            selfVerifiedAt: new Date().toISOString(),
          });

          await markAgentVerified(mainOperatorId);

          if (issueId) {
            await addIssueComment(
              issueId,
              `Self verification completed. Status: verified. Operator identity confirmed via Self Protocol.`
            ).catch(() => {});
          }
        })
        .catch(() => {
          // waitForCompletion often fails with session token issues
          // Keep as pending — the check action will use on-chain verification
        });

      return NextResponse.json({
        success: true,
        deepLink: session.deepLink,
        agentAddress: session.agentAddress,
        instructions: session.humanInstructions,
        expiresAt: session.expiresAt,
      });
    }

    if (action === "check") {
      // 1. Check trust store first
      const currentState = getTrustState(companyId);
      if (currentState.selfVerified) {
        activeSessions.delete(companyId);
        return NextResponse.json({
          success: true,
          verified: true,
          state: currentState,
        });
      }

      // 2. Check if background waitForCompletion succeeded
      const entry = activeSessions.get(companyId);
      if (entry?.status === "completed") {
        activeSessions.delete(companyId);
        const state = updateTrustState(companyId, {
          selfVerified: true,
          selfVerifiedAt: new Date().toISOString(),
        });
        await markAgentVerified(mainOperatorId);
        return NextResponse.json({ success: true, verified: true, state });
      }

      // 3. Still pending — rely on waitForCompletion callback or manual "Confirm" button
      // Do NOT check isRegistered() here — it returns true from previous registrations
      // and causes the QR code to auto-close before the user scans
      return NextResponse.json({
        success: true,
        verified: false,
        pending: !!entry,
      });
    }

    if (action === "confirm") {
      // Manual confirm — ONLY check the specific agent address from THIS company's session
      const { checkSelfAgentOnChain } = await import("@/lib/self-onchain");

      // Get this company's session agent address (in-memory or persisted)
      const entry = activeSessions.get(companyId);
      const currentState = getTrustState(companyId);
      const agentAddr = entry?.agentAddress || currentState.selfAgentAddress;

      if (!agentAddr) {
        return NextResponse.json({
          success: false,
          verified: false,
          error: "No verification session found. Click 'Verify' first to start a session, then scan the QR code.",
        });
      }

      // Check ONLY this company's agent address on-chain
      const result = await checkSelfAgentOnChain(agentAddr as `0x${string}`);

      if (result.isVerified) {
        activeSessions.delete(companyId);
        const state = updateTrustState(companyId, {
          selfVerified: true,
          selfVerifiedAt: new Date().toISOString(),
        });
        await markAgentVerified(mainOperatorId);
        if (issueId) {
          await addIssueComment(
            issueId,
            `Self verification confirmed on-chain. Agent #${result.agentId} verified. Proof fresh: ${result.isProofFresh}. Expires: ${result.proofExpiresAt}. Owner: ${result.owner}.`
          ).catch(() => {});
        }
        return NextResponse.json({
          success: true,
          verified: true,
          onChain: true,
          agentId: result.agentId,
          agentAddress: agentAddr,
          hasHumanProof: result.hasHumanProof,
          isProofFresh: result.isProofFresh,
          proofExpiresAt: result.proofExpiresAt,
          owner: result.owner,
          state,
        });
      }

      // Agent not verified on-chain yet
      return NextResponse.json({
        success: true,
        verified: false,
        agentAddress: agentAddr,
        message: "Agent not verified on-chain yet. Please scan the QR code in the Self app first.",
      });
    }

    return NextResponse.json(
      { error: "Invalid action. Use 'start', 'check', or 'confirm'" },
      { status: 400 }
    );
  } catch (e) {
    return NextResponse.json(
      { error: (e as Error).message },
      { status: 500 }
    );
  }
}
